include: ["_pages"]
search: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      author_profile: true
      read_time: true
      toc: true

title: Amrit
description: >-
  Random musings about programming, tech and engineering.
twitter_username: amritk110
github_username:  amrit110

# Build settings
remote_theme: "amrit110/minimal-mistakes" # point to my fork
minimal_mistakes_skin: dark
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji

author:
  name: "Amrit"
  avatar: /assets/images/bio-photo.png
  bio: >
    I'm an engineer who likes to play around with challenging problems involving programming.<br><br>
    This is where I can share random thoughts and encounters with problems in engineering.
  location: "Earth"
  links:
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amrit110"
    - label: "twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/amritk110"
